
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'BasicCompany.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: | 
     **\*Tests.dll
     !**\*UITests.dll
    runInParallel: true
    codeCoverageEnabled: true


- task: CopyFiles@2
  displayName: 'Copy automation tests'
  inputs:
    SourceFolder: '$(Build.sourcesdirectory)/src/Project/BasicCompany/tests'
    Contents: '**'
    TargetFolder: '$(Build.artifactstagingdirectory)/UITests'
    flattenFolders: false

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
